#[cfg(doc)]
use crate::HHOOK;
use winsafe::HOOKPROC;
use winsafe::co::WH;

use crate::{SysError, ThreadId, WindowsHook, module::Module};

/// A safe wrapper around a [`HHOOK`] for a the [`WH::KEYBOARD_LL`] keyboard hook.
///
/// # Examples
///
/// ```rust
/// use windows_hook::KeyboardLLHook;
/// # use windows_hook::{WindowsHook, WH, Handle, HHOOK};
/// # extern "system" fn your_hook_fn(code: i32, wparam: usize, lparam: isize) -> isize {
/// #   HHOOK::NULL.CallNextHookEx(unsafe { WH::from_raw(code) }, wparam, lparam)
/// # }
/// # fn main() -> Result<(), Box<dyn std::error::Error>> {
/// let hook = KeyboardLLHook::set_new(your_hook_fn)?;
///
/// assert!(hook.state().is_set());
///
/// // do stuff
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Default, derive_more::Deref, derive_more::DerefMut)]
pub struct KeyboardLLHook(WindowsHook);

impl KeyboardLLHook {
    /// Creates a new [`KeyboardLLHook`] and sets it.
    ///
    /// # Errors
    ///
    /// Returns any error generated by the os during `SetWindowsHookEx`.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use windows_hook::KeyboardLLHook;
    /// # use windows_hook::{WH, Handle, HHOOK};
    /// # extern "system" fn your_hook_fn(code: i32, wparam: usize, lparam: isize) -> isize {
    /// #   HHOOK::NULL.CallNextHookEx(unsafe { WH::from_raw(code) }, wparam, lparam)
    /// # }
    /// # fn main() -> Result<(), Box<dyn std::error::Error>> {
    ///
    /// let hook = KeyboardLLHook::set_new(your_hook_fn)?;
    ///
    /// assert!(hook.state().is_set());
    /// # Ok(())
    /// # }
    /// ```
    pub fn set_new(proc: HOOKPROC) -> Result<Self, SysError> {
        WindowsHook::set_new(WH::KEYBOARD_LL, proc, Module::NULL, ThreadId::NONE).map(Self)
    }
}
